In [20]:
import numpy as np

from matplotlib import pyplot as plt
from scipy import linalg
from sklearn.decomposition import PCA
from sklearn.metrics import mean_squared_error

## Уровень 0:

### Задание №1

In [6]:
# a) Диагональная, ортогональная, но не единичная(!)
m = np.diag([-1,  -1, -1])
print(m) # Не удалось подобрать одновременно диагональную и ортогональную и не единичную, поэтому взяла такой вариант

[[-1  0  0]
 [ 0 -1  0]
 [ 0  0 -1]]


In [9]:
det = np.linalg.det(m)
det

-1.0

In [11]:
# b) Верхнетреугольная, ортогональная
m_1 = np.triu([[-1, 0,  0,  0],
       [ 0, -1,  0,  0],
       [0,  0,  -1, 0],
       [ 0,  0, 0,  -1]], 0)
m_1

array([[-1,  0,  0,  0],
       [ 0, -1,  0,  0],
       [ 0,  0, -1,  0],
       [ 0,  0,  0, -1]])

In [12]:
det_1 = np.linalg.det(m_1)
det_1

1.0

In [13]:
# c) Нижнетреугольная, ортогональная
m_2 = np.tril([[-1, 0,  0,  0],
       [ 0, -1,  0,  0],
       [0,  0,  -1, 0],
       [ 0,  0, 0,  -1]], 0)
print(m_2)

[[-1  0  0  0]
 [ 0 -1  0  0]
 [ 0  0 -1  0]
 [ 0  0  0 -1]]


In [14]:
det_2 = np.linalg.det(m_2)
det_2

1.0

In [23]:
# d) Матрица, у которой определитель = 1, и все элементы не равны 0
m_3 = np.array([[1, 2] , [1, 3]])

In [24]:
det_3 = np.linalg.det(m_3)
det_3

1.0

### Задание №2

In [2]:
# Найдите собственные значения и собственные вектора матриц
m = np.array([[2, 2],
              [1, 3]])

In [6]:
w, v = np.linalg.eig(m)
print(w)
print(v)

[1. 4.]
[[-0.89442719 -0.70710678]
 [ 0.4472136  -0.70710678]]


In [37]:
for i in range(len(w)):
    print("Собственное значение " + str(w[i]))
    print("соответствующий ему собственный вектор " + str(v[:,i]))

Собственное значение 1.0
соответствующий ему собственный вектор [-0.89442719  0.4472136 ]
Собственное значение 4.0
соответствующий ему собственный вектор [-0.70710678 -0.70710678]


## Уровень 1:

### Задание №1

In [36]:
# Спектральное разложение матрицы
n = np.array([[1, 2],
              [2,3]])

In [44]:
a, U = linalg.eig(n)
print('Eigenvalues:')
print(np.array(a, dtype=float))
print('\nEigenvectors:')
print(U)

Eigenvalues:
[-0.23606798  4.23606798]

Eigenvectors:
[[-0.85065081 -0.52573111]
 [ 0.52573111 -0.85065081]]


In [45]:
print(np.array(U.dot(np.diag(a)).dot(U.T), dtype=float))

[[1. 2.]
 [2. 3.]]
