In [66]:
import numpy as np
from scipy.optimize import approx_fprime
from scipy.misc import derivative 
from sympy import *
from scipy.optimize import minimize

### Уровень 0:
#### Посчитайте частные производные функций:
#### 1) f(x,y)=2x^2y^3 + 1/x + y^2x + 7, а для этой функции также градиент в точке (1,2)
#### 2) f(x,y)=x^2y - sin(xy) + cos(x^2) + 6y

In [65]:
x,y,x_1, y_1 = symbols('x y x_1 y_1')

In [68]:
f_1 = 2*x**2*y**3 + 1/x + x*y**2 + 7
f_2 = x_1**2*y_1 - sin(x_1*y_1) + cos(x_1**2) + 6*y_1

In [69]:
dif_1 = diff(f_1, x)
dif_2 = diff(f_1, y)
print("Частная производная по x : {}".format(dif_1))
print("Частная производная по y : {}".format(dif_2))

Частная производная по x : 4*x*y**3 + y**2 - 1/x**2
Частная производная по y : 6*x**2*y**2 + 2*x*y


In [70]:
dif_3 = diff(f_2, x_1)
dif_4 = diff(f_2, y_1)
print("Частная производная по x_1 : {}".format(dif_3))
print("Частная производная по y_1 : {}".format(dif_4))

Частная производная по x_1 : 2*x_1*y_1 - 2*x_1*sin(x_1**2) - y_1*cos(x_1*y_1)
Частная производная по y_1 : x_1**2 - x_1*cos(x_1*y_1) + 6


In [72]:
x_ = np.array([1,2]) # Градиент в точке (1,2)
eps = np.sqrt(np.finfo(float).eps)

In [74]:
def func(x_):
    return 2*x_[0]**2*x_[1]**3 + 1/x_[0] + x_[0]*x_[1]**2 + 7 
# Первая производная функции f_1 по x, в которую подставлены значения градиенты вместо x и y

In [76]:
approx_fprime(x_, func, [eps, eps])

array([35.00000024, 28.00000024])

### Уровень 1:
#### Градиентный спуск своими руками:

In [109]:
def f_(x__):
    return (x_[0]**2) + (x_[1]**2)

In [117]:
x_current = np.array([100, 200])
x_previos = np.array([100, 200])
learning_rate = 0.1

In [120]:
grad = approx_fprime(x_previos, f_, [eps, eps])
grad

array([0., 0.])

In [121]:
x_current = x_previos - learning_rate*grad
x_current

array([100., 200.])

In [118]:
for i in range(100):
    # Calculate gradient
    
    grad = approx_fprime(x_previos, f_, [eps, eps])
    # Your code here (функция для вычисления градиента есть в лекционном ноутбуке)
    
    # Update x with gradient
    x_current = x_previos - learning_rate*grad
    
    x_previous = x_current

In [119]:
print("Минимум достигается в: ", x_current)
print("Значение функции в минимуме: ", f_(x_current))

Минимум достигается в:  [100. 200.]
Значение функции в минимуме:  5


In [114]:
# Проверка с помощью встроенной функции numpy:
res = minimize(f_, x_current, method = 'nelder-mead' , options = { 'xtol' : 1e-8 , 'disp' : True })
res

Optimization terminated successfully.
         Current function value: 5.000000
         Iterations: 31
         Function evaluations: 123


 final_simplex: (array([[100.        , 200.        ],
       [100.        , 200.        ],
       [100.        , 200.00000001]]), array([5., 5., 5.]))
           fun: 5.0
       message: 'Optimization terminated successfully.'
          nfev: 123
           nit: 31
        status: 0
       success: True
             x: array([100., 200.])